<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ProjectDoorango</AssemblyName>
    <Version>0.1.3</Version>
    <ApplicationIcon>Assets/Doorango.ico</ApplicationIcon>
    <StartupObject>ProjectDoorango.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets/Doorango.ico" />
    <Resource Include="Assets/Doorango.png" />
  </ItemGroup>
</Project>
